const CONFIG = {
  BOARD: {
    ROWS: 10,
    COLS: 11,
    TILE_SIZE: 45,
    OFFSET_X: 45,
    OFFSET_Y: 35,
  },
  GAME: {
    TIME_LIMIT_SECONDS: 600,
  },
  ANIMATION: {
    SPEED: 0.005,
    HOVER_MIN: 0.1,
    HOVER_MAX: 0.3,
    MOVE_MIN: 0.3,
    MOVE_MAX: 0.7,
  },
  THEME: {
    BOARD_LIGHT: "#56565633",
    BOARD_DARK: "#29292933",
    GRID_LINE: "rgba(255, 255, 255, 0.3)",
    CITADEL: "rgba(142, 68, 173, 0.6)",

    COLOR_HOVER: [255, 255, 255],
    COLOR_VALID: [46, 204, 113],
    COLOR_CAPTURE: [241, 196, 15],
    COLOR_INVALID: [231, 76, 60],
    COLOR_SELECTED: "#f1c40f",

    PIECE_WHITE: "#ecf0f1",
    PIECE_WHITE_STROKE: "#2c3e50",
    PIECE_BLACK: "#2c3e50",
    PIECE_BLACK_STROKE: "#ecf0f1",
  },
  PROMOTION_MAP: {
    0: "rook",
    1: "knight",
    2: "camel",
    3: "giraffe",
    4: "catapult",
    5: "prince",
    6: "general",
    7: "catapult",
    8: "giraffe",
    9: "knight",
    10: "rook",
  },
  INITIAL_SETUP: [
    { t: "rook", c: "black", x: 0, y: 0 },
    { t: "knight", c: "black", x: 1, y: 0 },
    { t: "camel", c: "black", x: 2, y: 0 },
    { t: "elephant", c: "black", x: 3, y: 0 },
    { t: "vizier", c: "black", x: 4, y: 0 },
    { t: "king", c: "black", x: 5, y: 0 },
    { t: "general", c: "black", x: 6, y: 0 },
    { t: "elephant", c: "black", x: 7, y: 0 },
    { t: "camel", c: "black", x: 8, y: 0 },
    { t: "knight", c: "black", x: 9, y: 0 },
    { t: "rook", c: "black", x: 10, y: 0 },

    { t: "giraffe", c: "black", x: 0, y: 1 },
    { t: "scout", c: "black", x: 2, y: 1 },
    { t: "catapult", c: "black", x: 4, y: 1 },
    { t: "catapult", c: "black", x: 6, y: 1 },
    { t: "scout", c: "black", x: 8, y: 1 },
    { t: "giraffe", c: "black", x: 10, y: 1 },

    ...Array.from({ length: 11 }, (_, i) => ({
      t: "pawn",
      c: "black",
      x: i,
      y: 2,
    })),
    ...Array.from({ length: 11 }, (_, i) => ({
      t: "pawn",
      c: "white",
      x: i,
      y: 7,
    })),

    { t: "giraffe", c: "white", x: 0, y: 8 },
    { t: "scout", c: "white", x: 2, y: 8 },
    { t: "catapult", c: "white", x: 4, y: 8 },
    { t: "catapult", c: "white", x: 6, y: 8 },
    { t: "scout", c: "white", x: 8, y: 8 },
    { t: "giraffe", c: "white", x: 10, y: 8 },

    { t: "rook", c: "white", x: 0, y: 9 },
    { t: "knight", c: "white", x: 1, y: 9 },
    { t: "camel", c: "white", x: 2, y: 9 },
    { t: "elephant", c: "white", x: 3, y: 9 },
    { t: "general", c: "white", x: 4, y: 9 },
    { t: "king", c: "white", x: 5, y: 9 },
    { t: "vizier", c: "white", x: 6, y: 9 },
    { t: "elephant", c: "white", x: 7, y: 9 },
    { t: "camel", c: "white", x: 8, y: 9 },
    { t: "knight", c: "white", x: 9, y: 9 },
    { t: "rook", c: "white", x: 10, y: 9 },
  ],
};
